## Welcome

These are the materials for a workshop on Quarto by [Julia Silge](https://juliasilge.com/) at [CIPPCD 2025](https://cippcd2025.eventqualia.net/) in Aveiro, Portugal on 17 May 2025. Quarto is an innovative, open-source scientific and technical publishing system compatible with Jupyter Notebooks and plain text markdown documents. Quarto provides data scientists with a seamless way to publish their work in a high-quality format that is reproducible, accessible, and shareable. With Quarto, data scientists working in public policy can turn their Jupyter Notebooks and literate plain text markdown documents into professional-looking publications in various formats. This workshop will demonstrate how Quarto enables data scientists to turn their work products into professional, high-quality documents, slides, websites, and other shareable artifacts.

This workshop is based on the materials developed by [Mine Çetinkaya-Rundel](https://mine-cr.com/) for [SciPy 2024](https://github.com/mine-cetinkaya-rundel/quarto-scipy24).

## Learning objectives: 

At the end of this workshop, participants will understand how to: 

-   Author documents in plain text markdown or Jupyter notebooks with equations, citations, crossrefs, figure panels, callouts, and advanced layouts.
-   Learn how to author content in IPython/Jupyter and the Quarto VS Code extension.
-   Leverage Quarto for creating different types of publications, including webpages/blogs, slides, dashboards, books, websites, and scientific manuscripts.
-   Customize execution and content with a rich array of code cell options, filters, and extensions.
-   Host websites and publications on platforms such as GitHub Pages, QuartoPub, and Netlify.


## Preparation

Please create a [GitHub](https://github.com/) account ahead of time, to use a cloud workspace via [Codespaces](https://github.com/features/codespaces) during the workshop. The [free tier](https://docs.github.com/en/billing/managing-billing-for-your-products/managing-billing-for-github-codespaces/about-billing-for-github-codespaces) will be adequate for our workshop. Do remember to bring your laptop to work along!

Alternatively, if you prefer to work locally, please tune into the workshop with a computer that has the following installed (all available for free):

- A recent version of Python (perhaps installed using [pyenv](https://github.com/pyenv/pyenv))
- [Quarto](https://quarto.org/docs/get-started/)
- Install VS Code and the [Quarto](https://marketplace.visualstudio.com/items?itemName=quarto.quarto) and [Jupyter](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter) extensions (or [Positron](https://positron.posit.co/download)!)
- Clone the [repo](https://github.com/juliasilge/cippcd-2025)
- Install the Python packages from `requirements.txt`


## Slides

- 01: [Hello, Quarto!](slides/01-hello-quarto.html)
- 02: [Documents](slides/02-documents.html)
- 03: [Presentations](slides/03-presentations.html)
- 04: [Dashboards](slides/04-dashboards.html)
- 05: [Websites and blogs](slides/05-websites.html)
- 06: [Books](slides/06-books.html)

## Code

Quarto files for working along [are available on GitHub](https://github.com/juliasilge/cippcd-2025/tree/master/code).

## Instructor bio

Julia Silge is a data scientist and engineering manager at [Posit PBC](https://posit.co/) (formerly RStudio), where she leads a team of developers building fluent, cohesive open source software for data science in Python and R. She is an author, an international keynote speaker, and a real-world practitioner focusing on data analysis and machine learning. Julia loves text analysis, making beautiful charts, and communicating about technical topics with diverse audiences.
